#Name: Kaiqi Chee
#Pledge: I pledge my honor that I have abided by the Stevens Honor System.
CC     = gcc
CFLAGS = -g -Wall -Werror -pedantic-errors

all:
	$(CC) $(CFLAGS) chatserver.c -o chatserver
	$(CC) $(CFLAGS) chatclient.c -o chatclient
	
clean:
	rm -f $(TARGET) $(TARGET).exe
